name: 'cbibs_pipeline'
version: '1.0.0'
config-version: 2
profile: 'cbibs_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  cbibs_pipeline:
    staging:
      +materialized: view
      +schema: staging_data
    intermediate:
      +materialized: table
      +schema: intermediate_data
    mart:
      +materialized: table
      +schema: production_data
