version: 2

sources:
  - name: raw
    database: "{{ env_var('DBT_PROJECT') }}"
    schema: raw_data
    tables:
      - name: api_raw_data

models:
  - name: stg_stations
    columns:
      - name: station_short_name
        data_tests:
          - unique
          - not_null
  - name: stg_measurements
    columns:
      - name: measurement_id
        data_tests:
          - unique
          - not_null